=== kitajima2910/learn-java/MLJ/Lab/BaiThucHanh1/build/classes/com/hoaipx/xml/assignment-3.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT courierList (courier)*>

<!ENTITY byair "by byair">
<!ENTITY bytrain "by bytrain">
<!ENTITY byship "by byship">
<!ENTITY bytruck "by bytruck">

    <!ELEMENT courier (despatch-details,courier-details,transportation)>
        <!ELEMENT despatch-details (Brfrom,Brto)>
            <!ELEMENT Brfrom (from-region,from-branch)>
                <!ELEMENT from-region (#PCDATA)>
                <!ELEMENT from-branch (#PCDATA)>
            <!ELEMENT Brto (to-region,to-branch)>
                <!ELEMENT to-region (#PCDATA)>
                <!ELEMENT to-branch (#PCDATA)>
        <!ELEMENT courier-details (from,to,buiding)>
            <!ATTLIST courier-details address-number CDATA #REQUIRED>
            <!ATTLIST courier-details street CDATA #REQUIRED>
            <!ELEMENT from (#PCDATA)>
            <!ELEMENT to (#PCDATA)>
            <!ELEMENT buiding EMPTY>
                <!ATTLIST buiding building-floor CDATA #REQUIRED>
                <!ATTLIST buiding room-no CDATA #REQUIRED>
        <!ELEMENT transportation (from-date,to-date)>
            <!ATTLIST transportation method ENTITY #REQUIRED>
            <!ELEMENT from-date (#PCDATA)>
            <!ELEMENT to-date (#PCDATA)>

=== kitajima2910/learn-java/MLJ/Lab/BaiThucHanh1/build/classes/com/hoaipx/xml/assignment-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE courierList SYSTEM "assignment-3.dtd" >

<courierList>
    <courier>
        <despatch-details>
            <Brfrom>
                <from-region>Văn phòng gửi 1</from-region>
                <from-branch>Chi nhanh gửi 1</from-branch>
            </Brfrom>
            <Brto>
                <to-region>Văn phòng nhận 1</to-region>
                <to-branch>Chi nhanh nhận 1</to-branch>
            </Brto>
        </despatch-details>
        <courier-details address-number="address 1" street="street 1">
            <from>Địa chỉ người gửi 1</from>
            <to>Địa chỉ người nhận 1</to>
            <buiding building-floor="building-floor 1" room-no="room-no 1"/>
        </courier-details>
        <transportation method="&byair;">
            <from-date>from-date 1</from-date>
            <to-date>to-date 1</to-date>
        </transportation>
    </courier>
</courierList>
