=== kitajima2910/learn-java/MLJ/Lab/BaiThucHanh1/build/classes/com/hoaipx/xml/giaohang.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- danh sách giao hàng gồm 0..n hàng được giao -->
<!ELEMENT delivered-products (delivered-product)*>
<!-- Khai báo 2 entity về phương tiện giao hàng -->
<!ENTITY moto "by motor" >
<!ENTITY truck "by truck" >
<!-- Thông tin về mặt hàng được giao gồm phiếu hoá đơn, khách hàng -->
<!ELEMENT delivered-product (invoice, customer, product)>
<!-- hoá đơn: thẻ trống chỉ gồm 2 thuộc tính số hoá đơn, ngày -->
<!ELEMENT invoice EMPTY>
    <!ATTLIST invoice id CDATA #REQUIRED 
                      date CDATA #REQUIRED 
                      by ENTITY #REQUIRED>
<!-- khách hàng: tên, địa chỉ giao hàng -->
<!ELEMENT customer (name, address) >
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT address (#PCDATA)>
<!-- mặt hàng gồm id, tên, số lượng, đơn giá, chi id là thuộc tính -->
<!ELEMENT product (product-name, quantity, price)>
    <!ATTLIST product id CDATA #REQUIRED>
    <!ELEMENT product-name (#PCDATA)>
    <!ELEMENT quantity (#PCDATA)>
    <!ELEMENT price (#PCDATA)>

=== kitajima2910/learn-java/MLJ/Lab/BaiThucHanh1/build/classes/com/hoaipx/xml/giaohang.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE delivered-products SYSTEM 'giaohang.dtd'>

<delivered-products>
    <delivered-product>
        <invoice id="IV123" date="2008/03/11" by="&truck;"/>
        <customer>
            <name>Tuan Anh</name>
            <address>123 Le Thanh Ton 01</address>
        </customer>
        <product id="P00001">
            <product-name>TV Sony Wega 46 inches</product-name>
            <quantity>2</quantity>
            <price>$400</price>
        </product>
    </delivered-product>
</delivered-products>
